export const STRINGS = {
  cancel: "取消",
  createNewCategory: "新建分类",
  createCategory: "创建分类",
  categoryName: "分类名称",
  chooseColor: "选择颜色",
  noCategory: "无分类",
  chooseCategory: "选择分类（可选）",
  selectCategory: "选择分类",
  today: "今天",
  tomorrow: "明天",
  nextWeek: "下周",
  addTask: "添加任务",
  addSubtask: "添加子任务",
  timer: "计时器",
  habits: "习惯",
  settings: "设置",
  brand: "优事空间 PrioSpace",
  tagline: "专注 · 追踪 · 成就",
};
